//
// Copyright 2023 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: org/signal/chat/profile.proto

package profile

import (
	common "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/common"
	errors "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/errors"
	_ "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/require"
	_ "go.mau.fi/mautrix-signal/pkg/signalmeow/protobuf/rpc/tag"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialType int32

const (
	CredentialType_CREDENTIAL_TYPE_UNSPECIFIED          CredentialType = 0
	CredentialType_CREDENTIAL_TYPE_EXPIRING_PROFILE_KEY CredentialType = 1
)

// Enum value maps for CredentialType.
var (
	CredentialType_name = map[int32]string{
		0: "CREDENTIAL_TYPE_UNSPECIFIED",
		1: "CREDENTIAL_TYPE_EXPIRING_PROFILE_KEY",
	}
	CredentialType_value = map[string]int32{
		"CREDENTIAL_TYPE_UNSPECIFIED":          0,
		"CREDENTIAL_TYPE_EXPIRING_PROFILE_KEY": 1,
	}
)

func (x CredentialType) Enum() *CredentialType {
	p := new(CredentialType)
	*p = x
	return p
}

func (x CredentialType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialType) Descriptor() protoreflect.EnumDescriptor {
	return file_org_signal_chat_profile_proto_enumTypes[0].Descriptor()
}

func (CredentialType) Type() protoreflect.EnumType {
	return &file_org_signal_chat_profile_proto_enumTypes[0]
}

func (x CredentialType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialType.Descriptor instead.
func (CredentialType) EnumDescriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{0}
}

type SetProfileV1Request_AvatarChange int32

const (
	SetProfileV1Request_AVATAR_CHANGE_UNCHANGED SetProfileV1Request_AvatarChange = 0
	SetProfileV1Request_AVATAR_CHANGE_CLEAR     SetProfileV1Request_AvatarChange = 1
	SetProfileV1Request_AVATAR_CHANGE_UPDATE    SetProfileV1Request_AvatarChange = 2
)

// Enum value maps for SetProfileV1Request_AvatarChange.
var (
	SetProfileV1Request_AvatarChange_name = map[int32]string{
		0: "AVATAR_CHANGE_UNCHANGED",
		1: "AVATAR_CHANGE_CLEAR",
		2: "AVATAR_CHANGE_UPDATE",
	}
	SetProfileV1Request_AvatarChange_value = map[string]int32{
		"AVATAR_CHANGE_UNCHANGED": 0,
		"AVATAR_CHANGE_CLEAR":     1,
		"AVATAR_CHANGE_UPDATE":    2,
	}
)

func (x SetProfileV1Request_AvatarChange) Enum() *SetProfileV1Request_AvatarChange {
	p := new(SetProfileV1Request_AvatarChange)
	*p = x
	return p
}

func (x SetProfileV1Request_AvatarChange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetProfileV1Request_AvatarChange) Descriptor() protoreflect.EnumDescriptor {
	return file_org_signal_chat_profile_proto_enumTypes[1].Descriptor()
}

func (SetProfileV1Request_AvatarChange) Type() protoreflect.EnumType {
	return &file_org_signal_chat_profile_proto_enumTypes[1]
}

func (x SetProfileV1Request_AvatarChange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetProfileV1Request_AvatarChange.Descriptor instead.
func (SetProfileV1Request_AvatarChange) EnumDescriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{0, 0}
}

type SetProfileV1Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ciphertext of a name that users must set on the profile.
	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// An enum to indicate what change, if any, is made to the avatar with this request.
	AvatarChange SetProfileV1Request_AvatarChange `protobuf:"varint,2,opt,name=avatar_change,json=avatarChange,proto3,enum=org.signal.chat.profile.SetProfileV1Request_AvatarChange" json:"avatar_change,omitempty"`
	// The ciphertext of an emoji that users can set on their profile.
	AboutEmoji []byte `protobuf:"bytes,3,opt,name=about_emoji,json=aboutEmoji,proto3" json:"about_emoji,omitempty"`
	// The ciphertext of a description that users can set on their profile.
	About []byte `protobuf:"bytes,4,opt,name=about,proto3" json:"about,omitempty"`
	// The ciphertext of the phone-number sharing setting on the profile. 29-byte encrypted boolean.
	PhoneNumberSharing []byte `protobuf:"bytes,6,opt,name=phone_number_sharing,json=phoneNumberSharing,proto3" json:"phone_number_sharing,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetProfileV1Request) Reset() {
	*x = SetProfileV1Request{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProfileV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProfileV1Request) ProtoMessage() {}

func (x *SetProfileV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProfileV1Request.ProtoReflect.Descriptor instead.
func (*SetProfileV1Request) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{0}
}

func (x *SetProfileV1Request) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *SetProfileV1Request) GetAvatarChange() SetProfileV1Request_AvatarChange {
	if x != nil {
		return x.AvatarChange
	}
	return SetProfileV1Request_AVATAR_CHANGE_UNCHANGED
}

func (x *SetProfileV1Request) GetAboutEmoji() []byte {
	if x != nil {
		return x.AboutEmoji
	}
	return nil
}

func (x *SetProfileV1Request) GetAbout() []byte {
	if x != nil {
		return x.About
	}
	return nil
}

func (x *SetProfileV1Request) GetPhoneNumberSharing() []byte {
	if x != nil {
		return x.PhoneNumberSharing
	}
	return nil
}

type SetV1AvatarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The profile version. Required.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// The profile key commitment. Required if this is a new profile version.
	Commitment    []byte `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetV1AvatarRequest) Reset() {
	*x = SetV1AvatarRequest{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetV1AvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetV1AvatarRequest) ProtoMessage() {}

func (x *SetV1AvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetV1AvatarRequest.ProtoReflect.Descriptor instead.
func (*SetV1AvatarRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{1}
}

func (x *SetV1AvatarRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SetV1AvatarRequest) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

type SetV1AvatarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the policy and credential used by clients to upload an avatar to the CDN
	Form          *common.S3UploadForm `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetV1AvatarResponse) Reset() {
	*x = SetV1AvatarResponse{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetV1AvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetV1AvatarResponse) ProtoMessage() {}

func (x *SetV1AvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetV1AvatarResponse.ProtoReflect.Descriptor instead.
func (*SetV1AvatarResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{2}
}

func (x *SetV1AvatarResponse) GetForm() *common.S3UploadForm {
	if x != nil {
		return x.Form
	}
	return nil
}

type SetProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The profile version. Required.
	Version []byte `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// The ciphertext of a serialized Profile protobuf. Required.
	// 937 max length = 909 plaintext serialization + 28 bytes encryption overhead
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// The SHA-256 hash of the Profile ciphertext being replaced.
	// This is used an optimistic lock against concurrent changes.
	//
	// Optional, if this is the initial request to create a version.
	ExpectedCurrentDataHash []byte `protobuf:"bytes,3,opt,name=expected_current_data_hash,json=expectedCurrentDataHash,proto3" json:"expected_current_data_hash,omitempty"`
	// The current profile version being updated.
	// This is used as an optimistic lock against concurrent changes.
	//
	// Optional, if there is no current profile version for the account.
	ExpectedCurrentVersion []byte `protobuf:"bytes,4,opt,name=expected_current_version,json=expectedCurrentVersion,proto3" json:"expected_current_version,omitempty"`
	// The ciphertext of the MobileCoin wallet ID on the profile.
	PaymentAddress []byte `protobuf:"bytes,5,opt,name=payment_address,json=paymentAddress,proto3" json:"payment_address,omitempty"`
	// A list of badge IDs associated with the profile.
	BadgeIds []string `protobuf:"bytes,6,rep,name=badge_ids,json=badgeIds,proto3" json:"badge_ids,omitempty"`
	// The profile key commitment. Used to issue a profile key credential response.
	//
	// Required during the v1 -> v2 migration period. Afterwards will be optional, if this is an update to an existing version.
	Commitment []byte `protobuf:"bytes,7,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// An embedded v1 request. Required during the v1 -> v2 migration period.
	//
	// Because this is a temporary field during the migration, it has the highest
	// field number without serialization overhead. This is purely aesthetic.
	V1Request     *SetProfileV1Request `protobuf:"bytes,15,opt,name=v1Request,proto3" json:"v1Request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProfileRequest) Reset() {
	*x = SetProfileRequest{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProfileRequest) ProtoMessage() {}

func (x *SetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProfileRequest.ProtoReflect.Descriptor instead.
func (*SetProfileRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{3}
}

func (x *SetProfileRequest) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *SetProfileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SetProfileRequest) GetExpectedCurrentDataHash() []byte {
	if x != nil {
		return x.ExpectedCurrentDataHash
	}
	return nil
}

func (x *SetProfileRequest) GetExpectedCurrentVersion() []byte {
	if x != nil {
		return x.ExpectedCurrentVersion
	}
	return nil
}

func (x *SetProfileRequest) GetPaymentAddress() []byte {
	if x != nil {
		return x.PaymentAddress
	}
	return nil
}

func (x *SetProfileRequest) GetBadgeIds() []string {
	if x != nil {
		return x.BadgeIds
	}
	return nil
}

func (x *SetProfileRequest) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *SetProfileRequest) GetV1Request() *SetProfileV1Request {
	if x != nil {
		return x.V1Request
	}
	return nil
}

// Indicates that the account is not permitted to set a payment address,
// due to a disallowed country prefix on the account's phone number.
type PaymentsForbiddenInRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentsForbiddenInRegion) Reset() {
	*x = PaymentsForbiddenInRegion{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentsForbiddenInRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentsForbiddenInRegion) ProtoMessage() {}

func (x *PaymentsForbiddenInRegion) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentsForbiddenInRegion.ProtoReflect.Descriptor instead.
func (*PaymentsForbiddenInRegion) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{4}
}

// Indicates that the account does not have the Profiles v2 capability, which
// is required to call Profiles.SetProfile
type ProfilesV2CapabilityRequired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilesV2CapabilityRequired) Reset() {
	*x = ProfilesV2CapabilityRequired{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesV2CapabilityRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesV2CapabilityRequired) ProtoMessage() {}

func (x *ProfilesV2CapabilityRequired) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilesV2CapabilityRequired.ProtoReflect.Descriptor instead.
func (*ProfilesV2CapabilityRequired) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{5}
}

type SetProfileResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If the request included a v1 avatar change, this field contains the policy
	// and credential used by clients to upload an avatar to the CDN.
	//
	// Because this is a temporary field during the migration, it has the highest
	// field number without serialization overhead. This is purely aesthetic.
	V1AvatarUploadForm *common.S3UploadForm `protobuf:"bytes,15,opt,name=v1_avatar_upload_form,json=v1AvatarUploadForm,proto3,oneof" json:"v1_avatar_upload_form,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetProfileResult) Reset() {
	*x = SetProfileResult{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProfileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProfileResult) ProtoMessage() {}

func (x *SetProfileResult) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProfileResult.ProtoReflect.Descriptor instead.
func (*SetProfileResult) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{6}
}

func (x *SetProfileResult) GetV1AvatarUploadForm() *common.S3UploadForm {
	if x != nil {
		return x.V1AvatarUploadForm
	}
	return nil
}

type SetProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*SetProfileResponse_Result
	//	*SetProfileResponse_ExpectedDataWriteConflict
	//	*SetProfileResponse_PaymentsForbiddenInRegion
	//	*SetProfileResponse_ExpectedVersionWriteConflict
	Response      isSetProfileResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProfileResponse) Reset() {
	*x = SetProfileResponse{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProfileResponse) ProtoMessage() {}

func (x *SetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProfileResponse.ProtoReflect.Descriptor instead.
func (*SetProfileResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{7}
}

func (x *SetProfileResponse) GetResponse() isSetProfileResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SetProfileResponse) GetResult() *SetProfileResult {
	if x != nil {
		if x, ok := x.Response.(*SetProfileResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *SetProfileResponse) GetExpectedDataWriteConflict() *errors.FailedPrecondition {
	if x != nil {
		if x, ok := x.Response.(*SetProfileResponse_ExpectedDataWriteConflict); ok {
			return x.ExpectedDataWriteConflict
		}
	}
	return nil
}

func (x *SetProfileResponse) GetPaymentsForbiddenInRegion() *PaymentsForbiddenInRegion {
	if x != nil {
		if x, ok := x.Response.(*SetProfileResponse_PaymentsForbiddenInRegion); ok {
			return x.PaymentsForbiddenInRegion
		}
	}
	return nil
}

func (x *SetProfileResponse) GetExpectedVersionWriteConflict() *errors.FailedPrecondition {
	if x != nil {
		if x, ok := x.Response.(*SetProfileResponse_ExpectedVersionWriteConflict); ok {
			return x.ExpectedVersionWriteConflict
		}
	}
	return nil
}

type isSetProfileResponse_Response interface {
	isSetProfileResponse_Response()
}

type SetProfileResponse_Result struct {
	Result *SetProfileResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type SetProfileResponse_ExpectedDataWriteConflict struct {
	// The current data hash did not match the request's expectation, indicating
	// another device on the account may have written an update the caller does not know about.
	ExpectedDataWriteConflict *errors.FailedPrecondition `protobuf:"bytes,2,opt,name=expected_data_write_conflict,json=expectedDataWriteConflict,proto3,oneof"`
}

type SetProfileResponse_PaymentsForbiddenInRegion struct {
	// Payments are not permitted in the account's region, based on its phone
	// number or the caller's IP address if the account does not have a phone
	// number. The request should be retried without `payment_address.
	PaymentsForbiddenInRegion *PaymentsForbiddenInRegion `protobuf:"bytes,3,opt,name=payments_forbidden_in_region,json=paymentsForbiddenInRegion,proto3,oneof"`
}

type SetProfileResponse_ExpectedVersionWriteConflict struct {
	// The current version did not match the request's expectation, indicating
	// another device on the account may have created a new version the caller does not know about.
	ExpectedVersionWriteConflict *errors.FailedPrecondition `protobuf:"bytes,4,opt,name=expected_version_write_conflict,json=expectedVersionWriteConflict,proto3,oneof"`
}

func (*SetProfileResponse_Result) isSetProfileResponse_Response() {}

func (*SetProfileResponse_ExpectedDataWriteConflict) isSetProfileResponse_Response() {}

func (*SetProfileResponse_PaymentsForbiddenInRegion) isSetProfileResponse_Response() {}

func (*SetProfileResponse_ExpectedVersionWriteConflict) isSetProfileResponse_Response() {}

type GetProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ACI of the account for which to get profile data.
	AccountIdentifier *common.ServiceIdentifier `protobuf:"bytes,1,opt,name=account_identifier,json=accountIdentifier,proto3" json:"account_identifier,omitempty"`
	// The profile version to retrieve.
	Version []byte `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// The `etag` from the previous request for this Profile version. If
	// unchanged, the response will omit `profile` and `etag_matched` will be
	// `true`.
	Etag          []byte `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileRequest) GetAccountIdentifier() *common.ServiceIdentifier {
	if x != nil {
		return x.AccountIdentifier
	}
	return nil
}

func (x *GetProfileRequest) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GetProfileRequest) GetEtag() []byte {
	if x != nil {
		return x.Etag
	}
	return nil
}

type GetProfileAnonymousRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains the data necessary to request a profile.
	Request *GetProfileRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// Types that are valid to be assigned to Authentication:
	//
	//	*GetProfileAnonymousRequest_UnidentifiedAccessKey
	//	*GetProfileAnonymousRequest_GroupSendToken
	Authentication isGetProfileAnonymousRequest_Authentication `protobuf_oneof:"authentication"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProfileAnonymousRequest) Reset() {
	*x = GetProfileAnonymousRequest{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileAnonymousRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileAnonymousRequest) ProtoMessage() {}

func (x *GetProfileAnonymousRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileAnonymousRequest.ProtoReflect.Descriptor instead.
func (*GetProfileAnonymousRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{9}
}

func (x *GetProfileAnonymousRequest) GetRequest() *GetProfileRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetProfileAnonymousRequest) GetAuthentication() isGetProfileAnonymousRequest_Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *GetProfileAnonymousRequest) GetUnidentifiedAccessKey() []byte {
	if x != nil {
		if x, ok := x.Authentication.(*GetProfileAnonymousRequest_UnidentifiedAccessKey); ok {
			return x.UnidentifiedAccessKey
		}
	}
	return nil
}

func (x *GetProfileAnonymousRequest) GetGroupSendToken() []byte {
	if x != nil {
		if x, ok := x.Authentication.(*GetProfileAnonymousRequest_GroupSendToken); ok {
			return x.GroupSendToken
		}
	}
	return nil
}

type isGetProfileAnonymousRequest_Authentication interface {
	isGetProfileAnonymousRequest_Authentication()
}

type GetProfileAnonymousRequest_UnidentifiedAccessKey struct {
	// The unidentified access key for the targeted account.
	UnidentifiedAccessKey []byte `protobuf:"bytes,2,opt,name=unidentified_access_key,json=unidentifiedAccessKey,proto3,oneof"`
}

type GetProfileAnonymousRequest_GroupSendToken struct {
	// A group send endorsement token for the targeted account.
	GroupSendToken []byte `protobuf:"bytes,3,opt,name=group_send_token,json=groupSendToken,proto3,oneof"`
}

func (*GetProfileAnonymousRequest_UnidentifiedAccessKey) isGetProfileAnonymousRequest_Authentication() {
}

func (*GetProfileAnonymousRequest_GroupSendToken) isGetProfileAnonymousRequest_Authentication() {}

type AccountInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account identity key of the targeted account.
	IdentityKey []byte `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	// A checksum of the unidentified access key for the targeted account.
	UnidentifiedAccessKeyFingerprint []byte `protobuf:"bytes,2,opt,name=unidentified_access_key_fingerprint,json=unidentifiedAccessKeyFingerprint,proto3" json:"unidentified_access_key_fingerprint,omitempty"`
	// Whether the account has enabled sealed sender from anyone.
	UnrestrictedUnidentifiedAccess bool `protobuf:"varint,3,opt,name=unrestricted_unidentified_access,json=unrestrictedUnidentifiedAccess,proto3" json:"unrestricted_unidentified_access,omitempty"`
	// A list of the badges ids associated with the account. Metadata to display
	// badges may be obtained by cross-referencing badge ids with
	// RemoteConfiguration.GetBadges.
	BadgeIds      []string `protobuf:"bytes,4,rep,name=badge_ids,json=badgeIds,proto3" json:"badge_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{10}
}

func (x *AccountInfo) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *AccountInfo) GetUnidentifiedAccessKeyFingerprint() []byte {
	if x != nil {
		return x.UnidentifiedAccessKeyFingerprint
	}
	return nil
}

func (x *AccountInfo) GetUnrestrictedUnidentifiedAccess() bool {
	if x != nil {
		return x.UnrestrictedUnidentifiedAccess
	}
	return false
}

func (x *AccountInfo) GetBadgeIds() []string {
	if x != nil {
		return x.BadgeIds
	}
	return nil
}

type ProfileResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ciphertext of the requested version of the profile
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The ciphertext of the MobileCoin wallet ID on the profile.
	PaymentAddress []byte `protobuf:"bytes,2,opt,name=payment_address,json=paymentAddress,proto3" json:"payment_address,omitempty"`
	// Information about the targeted account
	AccountInfo *AccountInfo `protobuf:"bytes,3,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	// An entity tag for the profile. This may be used in subsequent requests
	// for this profile version to optimize bandwidth.
	//
	// Note that this hash will not match the expected_data_hash used on
	// SetProfile for concurrency control.
	//
	// Clients may validate that the value has been correctly calculated by
	// calculating a 10-byte truncated TupleHash256 as follows:
	//
	// ```
	// TupleHash256(S = "ProfileETag/v1", L = 80 bits, tuple = [
	//
	//	data,
	//	payment_address,
	//	account_info.identity_key,
	//	account_info.unidentified_access_key_fingerprint,
	//	account_info.unrestricted_unidentified_access ? 0x01 : 0x00,
	//	uint32BE(count(account_info.badge_ids)),
	//	utf8(id) for each id in sortLexAscendingByUtf8Bytes(account_info.badge_ids),
	//
	// ])
	// ```
	//
	// Absent/empty fields contribute an empty element (not zero bytes omitted):
	// a missing payment_address is still a present, zero-length tuple element.
	//
	// This etag will always exclusively cover the documented fields. If fields
	// are added in the future, a new etag field must be introduced.
	Etag          []byte `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResult) Reset() {
	*x = ProfileResult{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResult) ProtoMessage() {}

func (x *ProfileResult) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResult.ProtoReflect.Descriptor instead.
func (*ProfileResult) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{11}
}

func (x *ProfileResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProfileResult) GetPaymentAddress() []byte {
	if x != nil {
		return x.PaymentAddress
	}
	return nil
}

func (x *ProfileResult) GetAccountInfo() *AccountInfo {
	if x != nil {
		return x.AccountInfo
	}
	return nil
}

func (x *ProfileResult) GetEtag() []byte {
	if x != nil {
		return x.Etag
	}
	return nil
}

type LegacyProfileResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ciphertext of the name on the profile.
	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The ciphertext of the description on the profile.
	About []byte `protobuf:"bytes,2,opt,name=about,proto3" json:"about,omitempty"`
	// The ciphertext of the emoji on the profile.
	AboutEmoji []byte `protobuf:"bytes,3,opt,name=about_emoji,json=aboutEmoji,proto3" json:"about_emoji,omitempty"`
	// The cdn0 path of the avatar on the profile.
	Avatar string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// The ciphertext of the phone-number sharing setting on the profile.
	PhoneNumberSharing []byte `protobuf:"bytes,5,opt,name=phone_number_sharing,json=phoneNumberSharing,proto3" json:"phone_number_sharing,omitempty"`
	// The ciphertext of the MobileCoin wallet ID on the profile.
	PaymentAddress []byte `protobuf:"bytes,6,opt,name=payment_address,json=paymentAddress,proto3" json:"payment_address,omitempty"`
	// Information about the targeted account
	AccountInfo   *AccountInfo `protobuf:"bytes,7,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LegacyProfileResult) Reset() {
	*x = LegacyProfileResult{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegacyProfileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegacyProfileResult) ProtoMessage() {}

func (x *LegacyProfileResult) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegacyProfileResult.ProtoReflect.Descriptor instead.
func (*LegacyProfileResult) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{12}
}

func (x *LegacyProfileResult) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *LegacyProfileResult) GetAbout() []byte {
	if x != nil {
		return x.About
	}
	return nil
}

func (x *LegacyProfileResult) GetAboutEmoji() []byte {
	if x != nil {
		return x.AboutEmoji
	}
	return nil
}

func (x *LegacyProfileResult) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LegacyProfileResult) GetPhoneNumberSharing() []byte {
	if x != nil {
		return x.PhoneNumberSharing
	}
	return nil
}

func (x *LegacyProfileResult) GetPaymentAddress() []byte {
	if x != nil {
		return x.PaymentAddress
	}
	return nil
}

func (x *LegacyProfileResult) GetAccountInfo() *AccountInfo {
	if x != nil {
		return x.AccountInfo
	}
	return nil
}

type GetProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetProfileResponse_Profile
	//	*GetProfileResponse_EtagMatched
	//	*GetProfileResponse_NotFound
	//	*GetProfileResponse_LegacyProfile
	Response      isGetProfileResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{13}
}

func (x *GetProfileResponse) GetResponse() isGetProfileResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetProfileResponse) GetProfile() *ProfileResult {
	if x != nil {
		if x, ok := x.Response.(*GetProfileResponse_Profile); ok {
			return x.Profile
		}
	}
	return nil
}

func (x *GetProfileResponse) GetEtagMatched() bool {
	if x != nil {
		if x, ok := x.Response.(*GetProfileResponse_EtagMatched); ok {
			return x.EtagMatched
		}
	}
	return false
}

func (x *GetProfileResponse) GetNotFound() *errors.NotFound {
	if x != nil {
		if x, ok := x.Response.(*GetProfileResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *GetProfileResponse) GetLegacyProfile() *LegacyProfileResult {
	if x != nil {
		if x, ok := x.Response.(*GetProfileResponse_LegacyProfile); ok {
			return x.LegacyProfile
		}
	}
	return nil
}

type isGetProfileResponse_Response interface {
	isGetProfileResponse_Response()
}

type GetProfileResponse_Profile struct {
	// The full profile data. The current profile did not match the provided
	// etag (or no etag was provided).
	Profile *ProfileResult `protobuf:"bytes,1,opt,name=profile,proto3,oneof"`
}

type GetProfileResponse_EtagMatched struct {
	// The current profile matched the provided etag. If present, this will always be true.
	EtagMatched bool `protobuf:"varint,2,opt,name=etag_matched,json=etagMatched,proto3,oneof"`
}

type GetProfileResponse_NotFound struct {
	NotFound *errors.NotFound `protobuf:"bytes,3,opt,name=not_found,json=notFound,proto3,oneof"`
}

type GetProfileResponse_LegacyProfile struct {
	// Will be present if there is no v2 Profile data for this version.
	//
	// Because this is a temporary field during the migration, it has the highest
	// field number without serialization overhead. This is purely aesthetic.
	LegacyProfile *LegacyProfileResult `protobuf:"bytes,15,opt,name=legacy_profile,json=legacyProfile,proto3,oneof"`
}

func (*GetProfileResponse_Profile) isGetProfileResponse_Response() {}

func (*GetProfileResponse_EtagMatched) isGetProfileResponse_Response() {}

func (*GetProfileResponse_NotFound) isGetProfileResponse_Response() {}

func (*GetProfileResponse_LegacyProfile) isGetProfileResponse_Response() {}

type GetProfileAnonymousResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetProfileAnonymousResponse_Profile
	//	*GetProfileAnonymousResponse_EtagMatched
	//	*GetProfileAnonymousResponse_NotFound
	//	*GetProfileAnonymousResponse_FailedUnidentifiedAuthorization
	//	*GetProfileAnonymousResponse_ProfileV1
	Response      isGetProfileAnonymousResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileAnonymousResponse) Reset() {
	*x = GetProfileAnonymousResponse{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileAnonymousResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileAnonymousResponse) ProtoMessage() {}

func (x *GetProfileAnonymousResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileAnonymousResponse.ProtoReflect.Descriptor instead.
func (*GetProfileAnonymousResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{14}
}

func (x *GetProfileAnonymousResponse) GetResponse() isGetProfileAnonymousResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetProfileAnonymousResponse) GetProfile() *ProfileResult {
	if x != nil {
		if x, ok := x.Response.(*GetProfileAnonymousResponse_Profile); ok {
			return x.Profile
		}
	}
	return nil
}

func (x *GetProfileAnonymousResponse) GetEtagMatched() bool {
	if x != nil {
		if x, ok := x.Response.(*GetProfileAnonymousResponse_EtagMatched); ok {
			return x.EtagMatched
		}
	}
	return false
}

func (x *GetProfileAnonymousResponse) GetNotFound() *errors.NotFound {
	if x != nil {
		if x, ok := x.Response.(*GetProfileAnonymousResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *GetProfileAnonymousResponse) GetFailedUnidentifiedAuthorization() *errors.FailedUnidentifiedAuthorization {
	if x != nil {
		if x, ok := x.Response.(*GetProfileAnonymousResponse_FailedUnidentifiedAuthorization); ok {
			return x.FailedUnidentifiedAuthorization
		}
	}
	return nil
}

func (x *GetProfileAnonymousResponse) GetProfileV1() *LegacyProfileResult {
	if x != nil {
		if x, ok := x.Response.(*GetProfileAnonymousResponse_ProfileV1); ok {
			return x.ProfileV1
		}
	}
	return nil
}

type isGetProfileAnonymousResponse_Response interface {
	isGetProfileAnonymousResponse_Response()
}

type GetProfileAnonymousResponse_Profile struct {
	// The full profile data. The current profile did not match the provided
	// etag (or no etag was provided).
	Profile *ProfileResult `protobuf:"bytes,1,opt,name=profile,proto3,oneof"`
}

type GetProfileAnonymousResponse_EtagMatched struct {
	// The current profile matched the provided etag. If present, this will always be true.
	EtagMatched bool `protobuf:"varint,2,opt,name=etag_matched,json=etagMatched,proto3,oneof"`
}

type GetProfileAnonymousResponse_NotFound struct {
	NotFound *errors.NotFound `protobuf:"bytes,3,opt,name=not_found,json=notFound,proto3,oneof"`
}

type GetProfileAnonymousResponse_FailedUnidentifiedAuthorization struct {
	FailedUnidentifiedAuthorization *errors.FailedUnidentifiedAuthorization `protobuf:"bytes,4,opt,name=failed_unidentified_authorization,json=failedUnidentifiedAuthorization,proto3,oneof"`
}

type GetProfileAnonymousResponse_ProfileV1 struct {
	// Will be present if there is no v2 Profile data for this version.
	//
	// Because this is a temporary field during the migration, it has the highest
	// field number without serialization overhead. This is purely aesthetic.
	ProfileV1 *LegacyProfileResult `protobuf:"bytes,15,opt,name=profile_v1,json=profileV1,proto3,oneof"`
}

func (*GetProfileAnonymousResponse_Profile) isGetProfileAnonymousResponse_Response() {}

func (*GetProfileAnonymousResponse_EtagMatched) isGetProfileAnonymousResponse_Response() {}

func (*GetProfileAnonymousResponse_NotFound) isGetProfileAnonymousResponse_Response() {}

func (*GetProfileAnonymousResponse_FailedUnidentifiedAuthorization) isGetProfileAnonymousResponse_Response() {
}

func (*GetProfileAnonymousResponse_ProfileV1) isGetProfileAnonymousResponse_Response() {}

type GetProfileKeyCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ACI of the account for which to get a profile key credential.
	AccountIdentifier *common.ServiceIdentifier `protobuf:"bytes,1,opt,name=account_identifier,json=accountIdentifier,proto3" json:"account_identifier,omitempty"`
	// A zkgroup request for a profile key credential for the target’s current profile.
	CredentialRequest []byte `protobuf:"bytes,2,opt,name=credential_request,json=credentialRequest,proto3" json:"credential_request,omitempty"`
	// The type of credential being requested.
	CredentialType CredentialType `protobuf:"varint,3,opt,name=credential_type,json=credentialType,proto3,enum=org.signal.chat.profile.CredentialType" json:"credential_type,omitempty"`
	// The unidentified access key for the targeted account.
	UnidentifiedAccessKey []byte `protobuf:"bytes,4,opt,name=unidentified_access_key,json=unidentifiedAccessKey,proto3" json:"unidentified_access_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetProfileKeyCredentialRequest) Reset() {
	*x = GetProfileKeyCredentialRequest{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileKeyCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileKeyCredentialRequest) ProtoMessage() {}

func (x *GetProfileKeyCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileKeyCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetProfileKeyCredentialRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{15}
}

func (x *GetProfileKeyCredentialRequest) GetAccountIdentifier() *common.ServiceIdentifier {
	if x != nil {
		return x.AccountIdentifier
	}
	return nil
}

func (x *GetProfileKeyCredentialRequest) GetCredentialRequest() []byte {
	if x != nil {
		return x.CredentialRequest
	}
	return nil
}

func (x *GetProfileKeyCredentialRequest) GetCredentialType() CredentialType {
	if x != nil {
		return x.CredentialType
	}
	return CredentialType_CREDENTIAL_TYPE_UNSPECIFIED
}

func (x *GetProfileKeyCredentialRequest) GetUnidentifiedAccessKey() []byte {
	if x != nil {
		return x.UnidentifiedAccessKey
	}
	return nil
}

type GetProfileKeyCredentialResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A zkgroup credential used by a client to prove that it has the profile key
	// of a targeted account.
	ProfileKeyCredential []byte `protobuf:"bytes,1,opt,name=profile_key_credential,json=profileKeyCredential,proto3" json:"profile_key_credential,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetProfileKeyCredentialResult) Reset() {
	*x = GetProfileKeyCredentialResult{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileKeyCredentialResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileKeyCredentialResult) ProtoMessage() {}

func (x *GetProfileKeyCredentialResult) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileKeyCredentialResult.ProtoReflect.Descriptor instead.
func (*GetProfileKeyCredentialResult) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{16}
}

func (x *GetProfileKeyCredentialResult) GetProfileKeyCredential() []byte {
	if x != nil {
		return x.ProfileKeyCredential
	}
	return nil
}

type GetProfileKeyCredentialResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetProfileKeyCredentialResponse_Result
	//	*GetProfileKeyCredentialResponse_NotFound
	//	*GetProfileKeyCredentialResponse_FailedUnidentifiedAuthorization
	Response      isGetProfileKeyCredentialResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileKeyCredentialResponse) Reset() {
	*x = GetProfileKeyCredentialResponse{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileKeyCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileKeyCredentialResponse) ProtoMessage() {}

func (x *GetProfileKeyCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileKeyCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetProfileKeyCredentialResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{17}
}

func (x *GetProfileKeyCredentialResponse) GetResponse() isGetProfileKeyCredentialResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetProfileKeyCredentialResponse) GetResult() *GetProfileKeyCredentialResult {
	if x != nil {
		if x, ok := x.Response.(*GetProfileKeyCredentialResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *GetProfileKeyCredentialResponse) GetNotFound() *errors.NotFound {
	if x != nil {
		if x, ok := x.Response.(*GetProfileKeyCredentialResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *GetProfileKeyCredentialResponse) GetFailedUnidentifiedAuthorization() *errors.FailedUnidentifiedAuthorization {
	if x != nil {
		if x, ok := x.Response.(*GetProfileKeyCredentialResponse_FailedUnidentifiedAuthorization); ok {
			return x.FailedUnidentifiedAuthorization
		}
	}
	return nil
}

type isGetProfileKeyCredentialResponse_Response interface {
	isGetProfileKeyCredentialResponse_Response()
}

type GetProfileKeyCredentialResponse_Result struct {
	Result *GetProfileKeyCredentialResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type GetProfileKeyCredentialResponse_NotFound struct {
	// Indicates the account was not found or the account's current profile was
	// not found. Use `AccountsAnonymous.CheckAccountExistence` for a canonical
	// account existence check.
	NotFound *errors.NotFound `protobuf:"bytes,2,opt,name=not_found,json=notFound,proto3,oneof"`
}

type GetProfileKeyCredentialResponse_FailedUnidentifiedAuthorization struct {
	// The provided unidentified access key was incorrect
	FailedUnidentifiedAuthorization *errors.FailedUnidentifiedAuthorization `protobuf:"bytes,3,opt,name=failed_unidentified_authorization,json=failedUnidentifiedAuthorization,proto3,oneof"`
}

func (*GetProfileKeyCredentialResponse_Result) isGetProfileKeyCredentialResponse_Response() {}

func (*GetProfileKeyCredentialResponse_NotFound) isGetProfileKeyCredentialResponse_Response() {}

func (*GetProfileKeyCredentialResponse_FailedUnidentifiedAuthorization) isGetProfileKeyCredentialResponse_Response() {
}

type GetAvatarCredentialRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	AvatarCredentialRequest []byte                 `protobuf:"bytes,1,opt,name=avatar_credential_request,json=avatarCredentialRequest,proto3" json:"avatar_credential_request,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetAvatarCredentialRequest) Reset() {
	*x = GetAvatarCredentialRequest{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvatarCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarCredentialRequest) ProtoMessage() {}

func (x *GetAvatarCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetAvatarCredentialRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{18}
}

func (x *GetAvatarCredentialRequest) GetAvatarCredentialRequest() []byte {
	if x != nil {
		return x.AvatarCredentialRequest
	}
	return nil
}

type GetAvatarCredentialResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetAvatarCredentialResponse_AvatarCredential
	//	*GetAvatarCredentialResponse_MissingZkCredentialKey
	Response      isGetAvatarCredentialResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvatarCredentialResponse) Reset() {
	*x = GetAvatarCredentialResponse{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvatarCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarCredentialResponse) ProtoMessage() {}

func (x *GetAvatarCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetAvatarCredentialResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{19}
}

func (x *GetAvatarCredentialResponse) GetResponse() isGetAvatarCredentialResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetAvatarCredentialResponse) GetAvatarCredential() []byte {
	if x != nil {
		if x, ok := x.Response.(*GetAvatarCredentialResponse_AvatarCredential); ok {
			return x.AvatarCredential
		}
	}
	return nil
}

func (x *GetAvatarCredentialResponse) GetMissingZkCredentialKey() *errors.FailedPrecondition {
	if x != nil {
		if x, ok := x.Response.(*GetAvatarCredentialResponse_MissingZkCredentialKey); ok {
			return x.MissingZkCredentialKey
		}
	}
	return nil
}

type isGetAvatarCredentialResponse_Response interface {
	isGetAvatarCredentialResponse_Response()
}

type GetAvatarCredentialResponse_AvatarCredential struct {
	AvatarCredential []byte `protobuf:"bytes,1,opt,name=avatar_credential,json=avatarCredential,proto3,oneof"`
}

type GetAvatarCredentialResponse_MissingZkCredentialKey struct {
	// the client must call Accounts.SetZkCredentialKey to call this method
	MissingZkCredentialKey *errors.FailedPrecondition `protobuf:"bytes,2,opt,name=missing_zk_credential_key,json=missingZkCredentialKey,proto3,oneof"`
}

func (*GetAvatarCredentialResponse_AvatarCredential) isGetAvatarCredentialResponse_Response() {}

func (*GetAvatarCredentialResponse_MissingZkCredentialKey) isGetAvatarCredentialResponse_Response() {}

type GetAvatarUploadFormRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	AvatarCredentialPresentation []byte                 `protobuf:"bytes,1,opt,name=avatar_credential_presentation,json=avatarCredentialPresentation,proto3" json:"avatar_credential_presentation,omitempty"`
	// The length of the attachment for the requested upload form. Uploads
	// performed with this form will be limited to the provided length.
	UploadLength  uint32 `protobuf:"varint,2,opt,name=upload_length,json=uploadLength,proto3" json:"upload_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvatarUploadFormRequest) Reset() {
	*x = GetAvatarUploadFormRequest{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvatarUploadFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarUploadFormRequest) ProtoMessage() {}

func (x *GetAvatarUploadFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarUploadFormRequest.ProtoReflect.Descriptor instead.
func (*GetAvatarUploadFormRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{20}
}

func (x *GetAvatarUploadFormRequest) GetAvatarCredentialPresentation() []byte {
	if x != nil {
		return x.AvatarCredentialPresentation
	}
	return nil
}

func (x *GetAvatarUploadFormRequest) GetUploadLength() uint32 {
	if x != nil {
		return x.UploadLength
	}
	return 0
}

type GetAvatarUploadFormResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetAvatarUploadFormResponse_AvatarUploadForm
	//	*GetAvatarUploadFormResponse_InvalidCredentialPresentation
	Response      isGetAvatarUploadFormResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvatarUploadFormResponse) Reset() {
	*x = GetAvatarUploadFormResponse{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvatarUploadFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvatarUploadFormResponse) ProtoMessage() {}

func (x *GetAvatarUploadFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvatarUploadFormResponse.ProtoReflect.Descriptor instead.
func (*GetAvatarUploadFormResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{21}
}

func (x *GetAvatarUploadFormResponse) GetResponse() isGetAvatarUploadFormResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetAvatarUploadFormResponse) GetAvatarUploadForm() *common.S3UploadForm {
	if x != nil {
		if x, ok := x.Response.(*GetAvatarUploadFormResponse_AvatarUploadForm); ok {
			return x.AvatarUploadForm
		}
	}
	return nil
}

func (x *GetAvatarUploadFormResponse) GetInvalidCredentialPresentation() *errors.FailedZkAuthentication {
	if x != nil {
		if x, ok := x.Response.(*GetAvatarUploadFormResponse_InvalidCredentialPresentation); ok {
			return x.InvalidCredentialPresentation
		}
	}
	return nil
}

type isGetAvatarUploadFormResponse_Response interface {
	isGetAvatarUploadFormResponse_Response()
}

type GetAvatarUploadFormResponse_AvatarUploadForm struct {
	// the policy and credential used by clients to upload an avatar to the CDN
	AvatarUploadForm *common.S3UploadForm `protobuf:"bytes,1,opt,name=avatar_upload_form,json=avatarUploadForm,proto3,oneof"`
}

type GetAvatarUploadFormResponse_InvalidCredentialPresentation struct {
	InvalidCredentialPresentation *errors.FailedZkAuthentication `protobuf:"bytes,2,opt,name=invalid_credential_presentation,json=invalidCredentialPresentation,proto3,oneof"`
}

func (*GetAvatarUploadFormResponse_AvatarUploadForm) isGetAvatarUploadFormResponse_Response() {}

func (*GetAvatarUploadFormResponse_InvalidCredentialPresentation) isGetAvatarUploadFormResponse_Response() {
}

type ExtendAvatarTTLRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	AvatarCredentialPresentation []byte                 `protobuf:"bytes,1,opt,name=avatar_credential_presentation,json=avatarCredentialPresentation,proto3" json:"avatar_credential_presentation,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ExtendAvatarTTLRequest) Reset() {
	*x = ExtendAvatarTTLRequest{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendAvatarTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendAvatarTTLRequest) ProtoMessage() {}

func (x *ExtendAvatarTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendAvatarTTLRequest.ProtoReflect.Descriptor instead.
func (*ExtendAvatarTTLRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{22}
}

func (x *ExtendAvatarTTLRequest) GetAvatarCredentialPresentation() []byte {
	if x != nil {
		return x.AvatarCredentialPresentation
	}
	return nil
}

type ExtendAvatarTTLResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ExtendAvatarTTLResponse_Path
	//	*ExtendAvatarTTLResponse_InvalidCredentialPresentation
	//	*ExtendAvatarTTLResponse_NotFound
	Response      isExtendAvatarTTLResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendAvatarTTLResponse) Reset() {
	*x = ExtendAvatarTTLResponse{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendAvatarTTLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendAvatarTTLResponse) ProtoMessage() {}

func (x *ExtendAvatarTTLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendAvatarTTLResponse.ProtoReflect.Descriptor instead.
func (*ExtendAvatarTTLResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{23}
}

func (x *ExtendAvatarTTLResponse) GetResponse() isExtendAvatarTTLResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ExtendAvatarTTLResponse) GetPath() string {
	if x != nil {
		if x, ok := x.Response.(*ExtendAvatarTTLResponse_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *ExtendAvatarTTLResponse) GetInvalidCredentialPresentation() *errors.FailedZkAuthentication {
	if x != nil {
		if x, ok := x.Response.(*ExtendAvatarTTLResponse_InvalidCredentialPresentation); ok {
			return x.InvalidCredentialPresentation
		}
	}
	return nil
}

func (x *ExtendAvatarTTLResponse) GetNotFound() *errors.NotFound {
	if x != nil {
		if x, ok := x.Response.(*ExtendAvatarTTLResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

type isExtendAvatarTTLResponse_Response interface {
	isExtendAvatarTTLResponse_Response()
}

type ExtendAvatarTTLResponse_Path struct {
	// The avatar that was extended. May be used as a check against state de-synchronization.
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type ExtendAvatarTTLResponse_InvalidCredentialPresentation struct {
	InvalidCredentialPresentation *errors.FailedZkAuthentication `protobuf:"bytes,2,opt,name=invalid_credential_presentation,json=invalidCredentialPresentation,proto3,oneof"`
}

type ExtendAvatarTTLResponse_NotFound struct {
	// the identity does not have an active avatar
	NotFound *errors.NotFound `protobuf:"bytes,3,opt,name=not_found,json=notFound,proto3,oneof"`
}

func (*ExtendAvatarTTLResponse_Path) isExtendAvatarTTLResponse_Response() {}

func (*ExtendAvatarTTLResponse_InvalidCredentialPresentation) isExtendAvatarTTLResponse_Response() {}

func (*ExtendAvatarTTLResponse_NotFound) isExtendAvatarTTLResponse_Response() {}

type DeleteAvatarRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	AvatarCredentialPresentation []byte                 `protobuf:"bytes,1,opt,name=avatar_credential_presentation,json=avatarCredentialPresentation,proto3" json:"avatar_credential_presentation,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *DeleteAvatarRequest) Reset() {
	*x = DeleteAvatarRequest{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarRequest) ProtoMessage() {}

func (x *DeleteAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarRequest.ProtoReflect.Descriptor instead.
func (*DeleteAvatarRequest) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteAvatarRequest) GetAvatarCredentialPresentation() []byte {
	if x != nil {
		return x.AvatarCredentialPresentation
	}
	return nil
}

type DeleteAvatarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*DeleteAvatarResponse_Success
	//	*DeleteAvatarResponse_InvalidCredentialPresentation
	Response      isDeleteAvatarResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarResponse) Reset() {
	*x = DeleteAvatarResponse{}
	mi := &file_org_signal_chat_profile_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarResponse) ProtoMessage() {}

func (x *DeleteAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_signal_chat_profile_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarResponse.ProtoReflect.Descriptor instead.
func (*DeleteAvatarResponse) Descriptor() ([]byte, []int) {
	return file_org_signal_chat_profile_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteAvatarResponse) GetResponse() isDeleteAvatarResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *DeleteAvatarResponse) GetSuccess() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Response.(*DeleteAvatarResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *DeleteAvatarResponse) GetInvalidCredentialPresentation() *errors.FailedZkAuthentication {
	if x != nil {
		if x, ok := x.Response.(*DeleteAvatarResponse_InvalidCredentialPresentation); ok {
			return x.InvalidCredentialPresentation
		}
	}
	return nil
}

type isDeleteAvatarResponse_Response interface {
	isDeleteAvatarResponse_Response()
}

type DeleteAvatarResponse_Success struct {
	Success *emptypb.Empty `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type DeleteAvatarResponse_InvalidCredentialPresentation struct {
	InvalidCredentialPresentation *errors.FailedZkAuthentication `protobuf:"bytes,2,opt,name=invalid_credential_presentation,json=invalidCredentialPresentation,proto3,oneof"`
}

func (*DeleteAvatarResponse_Success) isDeleteAvatarResponse_Response() {}

func (*DeleteAvatarResponse_InvalidCredentialPresentation) isDeleteAvatarResponse_Response() {}

var File_org_signal_chat_profile_proto protoreflect.FileDescriptor

const file_org_signal_chat_profile_proto_rawDesc = "" +
	"\n" +
	"\x1dorg/signal/chat/profile.proto\x12\x17org.signal.chat.profile\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1corg/signal/chat/common.proto\x1a\x1corg/signal/chat/errors.proto\x1a\x1dorg/signal/chat/require.proto\x1a\x19org/signal/chat/tag.proto\"\xf7\x02\n" +
	"\x13SetProfileV1Request\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\fB\a\xa2\x97\"\x03Q\x9d\x02R\x04name\x12^\n" +
	"\ravatar_change\x18\x02 \x01(\x0e29.org.signal.chat.profile.SetProfileV1Request.AvatarChangeR\favatarChange\x12'\n" +
	"\vabout_emoji\x18\x03 \x01(\fB\x06\xa2\x97\"\x02\x00<R\n" +
	"aboutEmoji\x12!\n" +
	"\x05about\x18\x04 \x01(\fB\v\xa2\x97\"\a\x00\x9c\x01\x9a\x02\x9c\x04R\x05about\x127\n" +
	"\x14phone_number_sharing\x18\x06 \x01(\fB\x05\xa2\x97\"\x01\x1dR\x12phoneNumberSharing\"^\n" +
	"\fAvatarChange\x12\x1b\n" +
	"\x17AVATAR_CHANGE_UNCHANGED\x10\x00\x12\x17\n" +
	"\x13AVATAR_CHANGE_CLEAR\x10\x01\x12\x18\n" +
	"\x14AVATAR_CHANGE_UPDATE\x10\x02\"]\n" +
	"\x12SetV1AvatarRequest\x12\x1f\n" +
	"\aversion\x18\x01 \x01(\tB\x05\xa2\x97\"\x01@R\aversion\x12&\n" +
	"\n" +
	"commitment\x18\x02 \x01(\fB\x06\xa2\x97\"\x02\x00aR\n" +
	"commitment\"O\n" +
	"\x13SetV1AvatarResponse\x128\n" +
	"\x04form\x18\x01 \x01(\v2$.org.signal.chat.common.S3UploadFormR\x04form\"\xa5\x03\n" +
	"\x11SetProfileRequest\x12\x1f\n" +
	"\aversion\x18\x01 \x01(\fB\x05\xa2\x97\"\x01 R\aversion\x12\x1f\n" +
	"\x04data\x18\x02 \x01(\fB\v\x88\x97\"\x01\x9a\x97\"\x03\x10\xa9\aR\x04data\x12C\n" +
	"\x1aexpected_current_data_hash\x18\x03 \x01(\fB\x06\xa2\x97\"\x02\x00 R\x17expectedCurrentDataHash\x12@\n" +
	"\x18expected_current_version\x18\x04 \x01(\fB\x06\xa2\x97\"\x02\x00 R\x16expectedCurrentVersion\x120\n" +
	"\x0fpayment_address\x18\x05 \x01(\fB\a\xa2\x97\"\x03\x00\xc6\x04R\x0epaymentAddress\x12\x1b\n" +
	"\tbadge_ids\x18\x06 \x03(\tR\bbadgeIds\x12&\n" +
	"\n" +
	"commitment\x18\a \x01(\fB\x06\xa2\x97\"\x02\x00aR\n" +
	"commitment\x12P\n" +
	"\tv1Request\x18\x0f \x01(\v2,.org.signal.chat.profile.SetProfileV1RequestB\x04\xb8\x97\"\x01R\tv1Request\"\x1b\n" +
	"\x19PaymentsForbiddenInRegion\"\x1e\n" +
	"\x1cProfilesV2CapabilityRequired\"\x8a\x01\n" +
	"\x10SetProfileResult\x12\\\n" +
	"\x15v1_avatar_upload_form\x18\x0f \x01(\v2$.org.signal.chat.common.S3UploadFormH\x00R\x12v1AvatarUploadForm\x88\x01\x01B\x18\n" +
	"\x16_v1_avatar_upload_form\"\xac\x04\n" +
	"\x12SetProfileResponse\x12C\n" +
	"\x06result\x18\x01 \x01(\v2).org.signal.chat.profile.SetProfileResultH\x00R\x06result\x12\x8f\x01\n" +
	"\x1cexpected_data_write_conflict\x18\x02 \x01(\v2*.org.signal.chat.errors.FailedPreconditionB \xc2\xd5\"\x1cexpected_data_write_conflictH\x00R\x19expectedDataWriteConflict\x12\x97\x01\n" +
	"\x1cpayments_forbidden_in_region\x18\x03 \x01(\v22.org.signal.chat.profile.PaymentsForbiddenInRegionB \xc2\xd5\"\x1cpayments_forbidden_in_regionH\x00R\x19paymentsForbiddenInRegion\x12\x98\x01\n" +
	"\x1fexpected_version_write_conflict\x18\x04 \x01(\v2*.org.signal.chat.errors.FailedPreconditionB#\xc2\xd5\"\x1fexpected_version_write_conflictH\x00R\x1cexpectedVersionWriteConflictB\n" +
	"\n" +
	"\bresponse\"\xb4\x01\n" +
	"\x11GetProfileRequest\x12b\n" +
	"\x12account_identifier\x18\x01 \x01(\v2).org.signal.chat.common.ServiceIdentifierB\b\xb8\x97\"\x01ȗ\"\x01R\x11accountIdentifier\x12\x1f\n" +
	"\aversion\x18\x02 \x01(\fB\x05\xa2\x97\"\x01 R\aversion\x12\x1a\n" +
	"\x04etag\x18\x03 \x01(\fB\x06\xa2\x97\"\x02\x00\n" +
	"R\x04etag\"\xed\x01\n" +
	"\x1aGetProfileAnonymousRequest\x12J\n" +
	"\arequest\x18\x01 \x01(\v2*.org.signal.chat.profile.GetProfileRequestB\x04\xb8\x97\"\x01R\arequest\x12?\n" +
	"\x17unidentified_access_key\x18\x02 \x01(\fB\x05\xa2\x97\"\x01\x10H\x00R\x15unidentifiedAccessKey\x120\n" +
	"\x10group_send_token\x18\x03 \x01(\fB\x04\x88\x97\"\x01H\x00R\x0egroupSendTokenB\x10\n" +
	"\x0eauthentication\"\xe6\x01\n" +
	"\vAccountInfo\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12M\n" +
	"#unidentified_access_key_fingerprint\x18\x02 \x01(\fR unidentifiedAccessKeyFingerprint\x12H\n" +
	" unrestricted_unidentified_access\x18\x03 \x01(\bR\x1eunrestrictedUnidentifiedAccess\x12\x1b\n" +
	"\tbadge_ids\x18\x04 \x03(\tR\bbadgeIds\"\xa9\x01\n" +
	"\rProfileResult\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12'\n" +
	"\x0fpayment_address\x18\x02 \x01(\fR\x0epaymentAddress\x12G\n" +
	"\faccount_info\x18\x03 \x01(\v2$.org.signal.chat.profile.AccountInfoR\vaccountInfo\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\fR\x04etag\"\x9c\x02\n" +
	"\x13LegacyProfileResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\fR\x04name\x12\x14\n" +
	"\x05about\x18\x02 \x01(\fR\x05about\x12\x1f\n" +
	"\vabout_emoji\x18\x03 \x01(\fR\n" +
	"aboutEmoji\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x120\n" +
	"\x14phone_number_sharing\x18\x05 \x01(\fR\x12phoneNumberSharing\x12'\n" +
	"\x0fpayment_address\x18\x06 \x01(\fR\x0epaymentAddress\x12G\n" +
	"\faccount_info\x18\a \x01(\v2$.org.signal.chat.profile.AccountInfoR\vaccountInfo\"\xd4\x02\n" +
	"\x12GetProfileResponse\x12B\n" +
	"\aprofile\x18\x01 \x01(\v2&.org.signal.chat.profile.ProfileResultH\x00R\aprofile\x123\n" +
	"\fetag_matched\x18\x02 \x01(\bB\x0e\xc2\xd5\"\n" +
	"etag_matchH\x00R\vetagMatched\x12N\n" +
	"\tnot_found\x18\x03 \x01(\v2 .org.signal.chat.errors.NotFoundB\r\xc2\xd5\"\tnot_foundH\x00R\bnotFound\x12i\n" +
	"\x0elegacy_profile\x18\x0f \x01(\v2,.org.signal.chat.profile.LegacyProfileResultB\x12\xc2\xd5\"\x0elegacy_profileH\x00R\rlegacyProfileB\n" +
	"\n" +
	"\bresponse\"\x80\x04\n" +
	"\x1bGetProfileAnonymousResponse\x12B\n" +
	"\aprofile\x18\x01 \x01(\v2&.org.signal.chat.profile.ProfileResultH\x00R\aprofile\x123\n" +
	"\fetag_matched\x18\x02 \x01(\bB\x0e\xc2\xd5\"\n" +
	"etag_matchH\x00R\vetagMatched\x12N\n" +
	"\tnot_found\x18\x03 \x01(\v2 .org.signal.chat.errors.NotFoundB\r\xc2\xd5\"\tnot_foundH\x00R\bnotFound\x12\xac\x01\n" +
	"!failed_unidentified_authorization\x18\x04 \x01(\v27.org.signal.chat.errors.FailedUnidentifiedAuthorizationB%\xc2\xd5\"!failed_unidentified_authorizationH\x00R\x1ffailedUnidentifiedAuthorization\x12]\n" +
	"\n" +
	"profile_v1\x18\x0f \x01(\v2,.org.signal.chat.profile.LegacyProfileResultB\x0e\xc2\xd5\"\n" +
	"profile_v1H\x00R\tprofileV1B\n" +
	"\n" +
	"\bresponse\"\xd0\x02\n" +
	"\x1eGetProfileKeyCredentialRequest\x12b\n" +
	"\x12account_identifier\x18\x01 \x01(\v2).org.signal.chat.common.ServiceIdentifierB\b\xb8\x97\"\x01ȗ\"\x01R\x11accountIdentifier\x123\n" +
	"\x12credential_request\x18\x02 \x01(\fB\x04\x88\x97\"\x01R\x11credentialRequest\x12V\n" +
	"\x0fcredential_type\x18\x03 \x01(\x0e2'.org.signal.chat.profile.CredentialTypeB\x04\x90\x97\"\x01R\x0ecredentialType\x12=\n" +
	"\x17unidentified_access_key\x18\x04 \x01(\fB\x05\xa2\x97\"\x01\x10R\x15unidentifiedAccessKey\"U\n" +
	"\x1dGetProfileKeyCredentialResult\x124\n" +
	"\x16profile_key_credential\x18\x01 \x01(\fR\x14profileKeyCredential\"\xfe\x02\n" +
	"\x1fGetProfileKeyCredentialResponse\x12P\n" +
	"\x06result\x18\x01 \x01(\v26.org.signal.chat.profile.GetProfileKeyCredentialResultH\x00R\x06result\x12N\n" +
	"\tnot_found\x18\x02 \x01(\v2 .org.signal.chat.errors.NotFoundB\r\xc2\xd5\"\tnot_foundH\x00R\bnotFound\x12\xac\x01\n" +
	"!failed_unidentified_authorization\x18\x03 \x01(\v27.org.signal.chat.errors.FailedUnidentifiedAuthorizationB%\xc2\xd5\"!failed_unidentified_authorizationH\x00R\x1ffailedUnidentifiedAuthorizationB\n" +
	"\n" +
	"\bresponse\"X\n" +
	"\x1aGetAvatarCredentialRequest\x12:\n" +
	"\x19avatar_credential_request\x18\x01 \x01(\fR\x17avatarCredentialRequest\"\xe1\x01\n" +
	"\x1bGetAvatarCredentialResponse\x12-\n" +
	"\x11avatar_credential\x18\x01 \x01(\fH\x00R\x10avatarCredential\x12\x86\x01\n" +
	"\x19missing_zk_credential_key\x18\x02 \x01(\v2*.org.signal.chat.errors.FailedPreconditionB\x1d\xc2\xd5\"\x19missing_zk_credential_keyH\x00R\x16missingZkCredentialKeyB\n" +
	"\n" +
	"\bresponse\"\x94\x01\n" +
	"\x1aGetAvatarUploadFormRequest\x12D\n" +
	"\x1eavatar_credential_presentation\x18\x01 \x01(\fR\x1cavatarCredentialPresentation\x120\n" +
	"\rupload_length\x18\x02 \x01(\rB\v\xb2\x97\"\a\b\x01\x10\x80\x80\x80\x05R\fuploadLength\"\x9f\x02\n" +
	"\x1bGetAvatarUploadFormResponse\x12T\n" +
	"\x12avatar_upload_form\x18\x01 \x01(\v2$.org.signal.chat.common.S3UploadFormH\x00R\x10avatarUploadForm\x12\x9d\x01\n" +
	"\x1finvalid_credential_presentation\x18\x02 \x01(\v2..org.signal.chat.errors.FailedZkAuthenticationB#\xc2\xd5\"\x1finvalid_credential_presentationH\x00R\x1dinvalidCredentialPresentationB\n" +
	"\n" +
	"\bresponse\"^\n" +
	"\x16ExtendAvatarTTLRequest\x12D\n" +
	"\x1eavatar_credential_presentation\x18\x01 \x01(\fR\x1cavatarCredentialPresentation\"\xb2\x02\n" +
	"\x17ExtendAvatarTTLResponse\x12\x14\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x12\x9d\x01\n" +
	"\x1finvalid_credential_presentation\x18\x02 \x01(\v2..org.signal.chat.errors.FailedZkAuthenticationB#\xc2\xd5\"\x1finvalid_credential_presentationH\x00R\x1dinvalidCredentialPresentation\x12U\n" +
	"\tnot_found\x18\x03 \x01(\v2 .org.signal.chat.errors.NotFoundB\x14\xc2\xd5\"\x10no_active_avatarH\x00R\bnotFoundB\n" +
	"\n" +
	"\bresponse\"[\n" +
	"\x13DeleteAvatarRequest\x12D\n" +
	"\x1eavatar_credential_presentation\x18\x01 \x01(\fR\x1cavatarCredentialPresentation\"\xf6\x01\n" +
	"\x14DeleteAvatarResponse\x122\n" +
	"\asuccess\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\asuccess\x12\x9d\x01\n" +
	"\x1finvalid_credential_presentation\x18\x02 \x01(\v2..org.signal.chat.errors.FailedZkAuthenticationB#\xc2\xd5\"\x1finvalid_credential_presentationH\x00R\x1dinvalidCredentialPresentationB\n" +
	"\n" +
	"\bresponse*[\n" +
	"\x0eCredentialType\x12\x1f\n" +
	"\x1bCREDENTIAL_TYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$CREDENTIAL_TYPE_EXPIRING_PROFILE_KEY\x10\x012\xd2\x03\n" +
	"\aProfile\x12g\n" +
	"\n" +
	"SetProfile\x12*.org.signal.chat.profile.SetProfileRequest\x1a+.org.signal.chat.profile.SetProfileResponse\"\x00\x12g\n" +
	"\n" +
	"GetProfile\x12*.org.signal.chat.profile.GetProfileRequest\x1a+.org.signal.chat.profile.GetProfileResponse\"\x00\x12\x82\x01\n" +
	"\x13GetAvatarCredential\x123.org.signal.chat.profile.GetAvatarCredentialRequest\x1a4.org.signal.chat.profile.GetAvatarCredentialResponse\"\x00\x12j\n" +
	"\vSetV1Avatar\x12+.org.signal.chat.profile.SetV1AvatarRequest\x1a,.org.signal.chat.profile.SetV1AvatarResponse\"\x00\x1a\x04\xc8\xd5\"\x012\x90\x05\n" +
	"\x10ProfileAnonymous\x12y\n" +
	"\n" +
	"GetProfile\x123.org.signal.chat.profile.GetProfileAnonymousRequest\x1a4.org.signal.chat.profile.GetProfileAnonymousResponse\"\x00\x12\x8e\x01\n" +
	"\x17GetProfileKeyCredential\x127.org.signal.chat.profile.GetProfileKeyCredentialRequest\x1a8.org.signal.chat.profile.GetProfileKeyCredentialResponse\"\x00\x12\x82\x01\n" +
	"\x13GetAvatarUploadForm\x123.org.signal.chat.profile.GetAvatarUploadFormRequest\x1a4.org.signal.chat.profile.GetAvatarUploadFormResponse\"\x00\x12v\n" +
	"\x0fExtendAvatarTTL\x12/.org.signal.chat.profile.ExtendAvatarTTLRequest\x1a0.org.signal.chat.profile.ExtendAvatarTTLResponse\"\x00\x12m\n" +
	"\fDeleteAvatar\x12,.org.signal.chat.profile.DeleteAvatarRequest\x1a-.org.signal.chat.profile.DeleteAvatarResponse\"\x00\x1a\x04\xc8\xd5\"\x02B\x02P\x01b\x06proto3"

var (
	file_org_signal_chat_profile_proto_rawDescOnce sync.Once
	file_org_signal_chat_profile_proto_rawDescData []byte
)

func file_org_signal_chat_profile_proto_rawDescGZIP() []byte {
	file_org_signal_chat_profile_proto_rawDescOnce.Do(func() {
		file_org_signal_chat_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_signal_chat_profile_proto_rawDesc), len(file_org_signal_chat_profile_proto_rawDesc)))
	})
	return file_org_signal_chat_profile_proto_rawDescData
}

var file_org_signal_chat_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_org_signal_chat_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_org_signal_chat_profile_proto_goTypes = []any{
	(CredentialType)(0),                            // 0: org.signal.chat.profile.CredentialType
	(SetProfileV1Request_AvatarChange)(0),          // 1: org.signal.chat.profile.SetProfileV1Request.AvatarChange
	(*SetProfileV1Request)(nil),                    // 2: org.signal.chat.profile.SetProfileV1Request
	(*SetV1AvatarRequest)(nil),                     // 3: org.signal.chat.profile.SetV1AvatarRequest
	(*SetV1AvatarResponse)(nil),                    // 4: org.signal.chat.profile.SetV1AvatarResponse
	(*SetProfileRequest)(nil),                      // 5: org.signal.chat.profile.SetProfileRequest
	(*PaymentsForbiddenInRegion)(nil),              // 6: org.signal.chat.profile.PaymentsForbiddenInRegion
	(*ProfilesV2CapabilityRequired)(nil),           // 7: org.signal.chat.profile.ProfilesV2CapabilityRequired
	(*SetProfileResult)(nil),                       // 8: org.signal.chat.profile.SetProfileResult
	(*SetProfileResponse)(nil),                     // 9: org.signal.chat.profile.SetProfileResponse
	(*GetProfileRequest)(nil),                      // 10: org.signal.chat.profile.GetProfileRequest
	(*GetProfileAnonymousRequest)(nil),             // 11: org.signal.chat.profile.GetProfileAnonymousRequest
	(*AccountInfo)(nil),                            // 12: org.signal.chat.profile.AccountInfo
	(*ProfileResult)(nil),                          // 13: org.signal.chat.profile.ProfileResult
	(*LegacyProfileResult)(nil),                    // 14: org.signal.chat.profile.LegacyProfileResult
	(*GetProfileResponse)(nil),                     // 15: org.signal.chat.profile.GetProfileResponse
	(*GetProfileAnonymousResponse)(nil),            // 16: org.signal.chat.profile.GetProfileAnonymousResponse
	(*GetProfileKeyCredentialRequest)(nil),         // 17: org.signal.chat.profile.GetProfileKeyCredentialRequest
	(*GetProfileKeyCredentialResult)(nil),          // 18: org.signal.chat.profile.GetProfileKeyCredentialResult
	(*GetProfileKeyCredentialResponse)(nil),        // 19: org.signal.chat.profile.GetProfileKeyCredentialResponse
	(*GetAvatarCredentialRequest)(nil),             // 20: org.signal.chat.profile.GetAvatarCredentialRequest
	(*GetAvatarCredentialResponse)(nil),            // 21: org.signal.chat.profile.GetAvatarCredentialResponse
	(*GetAvatarUploadFormRequest)(nil),             // 22: org.signal.chat.profile.GetAvatarUploadFormRequest
	(*GetAvatarUploadFormResponse)(nil),            // 23: org.signal.chat.profile.GetAvatarUploadFormResponse
	(*ExtendAvatarTTLRequest)(nil),                 // 24: org.signal.chat.profile.ExtendAvatarTTLRequest
	(*ExtendAvatarTTLResponse)(nil),                // 25: org.signal.chat.profile.ExtendAvatarTTLResponse
	(*DeleteAvatarRequest)(nil),                    // 26: org.signal.chat.profile.DeleteAvatarRequest
	(*DeleteAvatarResponse)(nil),                   // 27: org.signal.chat.profile.DeleteAvatarResponse
	(*common.S3UploadForm)(nil),                    // 28: org.signal.chat.common.S3UploadForm
	(*errors.FailedPrecondition)(nil),              // 29: org.signal.chat.errors.FailedPrecondition
	(*common.ServiceIdentifier)(nil),               // 30: org.signal.chat.common.ServiceIdentifier
	(*errors.NotFound)(nil),                        // 31: org.signal.chat.errors.NotFound
	(*errors.FailedUnidentifiedAuthorization)(nil), // 32: org.signal.chat.errors.FailedUnidentifiedAuthorization
	(*errors.FailedZkAuthentication)(nil),          // 33: org.signal.chat.errors.FailedZkAuthentication
	(*emptypb.Empty)(nil),                          // 34: google.protobuf.Empty
}
var file_org_signal_chat_profile_proto_depIdxs = []int32{
	1,  // 0: org.signal.chat.profile.SetProfileV1Request.avatar_change:type_name -> org.signal.chat.profile.SetProfileV1Request.AvatarChange
	28, // 1: org.signal.chat.profile.SetV1AvatarResponse.form:type_name -> org.signal.chat.common.S3UploadForm
	2,  // 2: org.signal.chat.profile.SetProfileRequest.v1Request:type_name -> org.signal.chat.profile.SetProfileV1Request
	28, // 3: org.signal.chat.profile.SetProfileResult.v1_avatar_upload_form:type_name -> org.signal.chat.common.S3UploadForm
	8,  // 4: org.signal.chat.profile.SetProfileResponse.result:type_name -> org.signal.chat.profile.SetProfileResult
	29, // 5: org.signal.chat.profile.SetProfileResponse.expected_data_write_conflict:type_name -> org.signal.chat.errors.FailedPrecondition
	6,  // 6: org.signal.chat.profile.SetProfileResponse.payments_forbidden_in_region:type_name -> org.signal.chat.profile.PaymentsForbiddenInRegion
	29, // 7: org.signal.chat.profile.SetProfileResponse.expected_version_write_conflict:type_name -> org.signal.chat.errors.FailedPrecondition
	30, // 8: org.signal.chat.profile.GetProfileRequest.account_identifier:type_name -> org.signal.chat.common.ServiceIdentifier
	10, // 9: org.signal.chat.profile.GetProfileAnonymousRequest.request:type_name -> org.signal.chat.profile.GetProfileRequest
	12, // 10: org.signal.chat.profile.ProfileResult.account_info:type_name -> org.signal.chat.profile.AccountInfo
	12, // 11: org.signal.chat.profile.LegacyProfileResult.account_info:type_name -> org.signal.chat.profile.AccountInfo
	13, // 12: org.signal.chat.profile.GetProfileResponse.profile:type_name -> org.signal.chat.profile.ProfileResult
	31, // 13: org.signal.chat.profile.GetProfileResponse.not_found:type_name -> org.signal.chat.errors.NotFound
	14, // 14: org.signal.chat.profile.GetProfileResponse.legacy_profile:type_name -> org.signal.chat.profile.LegacyProfileResult
	13, // 15: org.signal.chat.profile.GetProfileAnonymousResponse.profile:type_name -> org.signal.chat.profile.ProfileResult
	31, // 16: org.signal.chat.profile.GetProfileAnonymousResponse.not_found:type_name -> org.signal.chat.errors.NotFound
	32, // 17: org.signal.chat.profile.GetProfileAnonymousResponse.failed_unidentified_authorization:type_name -> org.signal.chat.errors.FailedUnidentifiedAuthorization
	14, // 18: org.signal.chat.profile.GetProfileAnonymousResponse.profile_v1:type_name -> org.signal.chat.profile.LegacyProfileResult
	30, // 19: org.signal.chat.profile.GetProfileKeyCredentialRequest.account_identifier:type_name -> org.signal.chat.common.ServiceIdentifier
	0,  // 20: org.signal.chat.profile.GetProfileKeyCredentialRequest.credential_type:type_name -> org.signal.chat.profile.CredentialType
	18, // 21: org.signal.chat.profile.GetProfileKeyCredentialResponse.result:type_name -> org.signal.chat.profile.GetProfileKeyCredentialResult
	31, // 22: org.signal.chat.profile.GetProfileKeyCredentialResponse.not_found:type_name -> org.signal.chat.errors.NotFound
	32, // 23: org.signal.chat.profile.GetProfileKeyCredentialResponse.failed_unidentified_authorization:type_name -> org.signal.chat.errors.FailedUnidentifiedAuthorization
	29, // 24: org.signal.chat.profile.GetAvatarCredentialResponse.missing_zk_credential_key:type_name -> org.signal.chat.errors.FailedPrecondition
	28, // 25: org.signal.chat.profile.GetAvatarUploadFormResponse.avatar_upload_form:type_name -> org.signal.chat.common.S3UploadForm
	33, // 26: org.signal.chat.profile.GetAvatarUploadFormResponse.invalid_credential_presentation:type_name -> org.signal.chat.errors.FailedZkAuthentication
	33, // 27: org.signal.chat.profile.ExtendAvatarTTLResponse.invalid_credential_presentation:type_name -> org.signal.chat.errors.FailedZkAuthentication
	31, // 28: org.signal.chat.profile.ExtendAvatarTTLResponse.not_found:type_name -> org.signal.chat.errors.NotFound
	34, // 29: org.signal.chat.profile.DeleteAvatarResponse.success:type_name -> google.protobuf.Empty
	33, // 30: org.signal.chat.profile.DeleteAvatarResponse.invalid_credential_presentation:type_name -> org.signal.chat.errors.FailedZkAuthentication
	5,  // 31: org.signal.chat.profile.Profile.SetProfile:input_type -> org.signal.chat.profile.SetProfileRequest
	10, // 32: org.signal.chat.profile.Profile.GetProfile:input_type -> org.signal.chat.profile.GetProfileRequest
	20, // 33: org.signal.chat.profile.Profile.GetAvatarCredential:input_type -> org.signal.chat.profile.GetAvatarCredentialRequest
	3,  // 34: org.signal.chat.profile.Profile.SetV1Avatar:input_type -> org.signal.chat.profile.SetV1AvatarRequest
	11, // 35: org.signal.chat.profile.ProfileAnonymous.GetProfile:input_type -> org.signal.chat.profile.GetProfileAnonymousRequest
	17, // 36: org.signal.chat.profile.ProfileAnonymous.GetProfileKeyCredential:input_type -> org.signal.chat.profile.GetProfileKeyCredentialRequest
	22, // 37: org.signal.chat.profile.ProfileAnonymous.GetAvatarUploadForm:input_type -> org.signal.chat.profile.GetAvatarUploadFormRequest
	24, // 38: org.signal.chat.profile.ProfileAnonymous.ExtendAvatarTTL:input_type -> org.signal.chat.profile.ExtendAvatarTTLRequest
	26, // 39: org.signal.chat.profile.ProfileAnonymous.DeleteAvatar:input_type -> org.signal.chat.profile.DeleteAvatarRequest
	9,  // 40: org.signal.chat.profile.Profile.SetProfile:output_type -> org.signal.chat.profile.SetProfileResponse
	15, // 41: org.signal.chat.profile.Profile.GetProfile:output_type -> org.signal.chat.profile.GetProfileResponse
	21, // 42: org.signal.chat.profile.Profile.GetAvatarCredential:output_type -> org.signal.chat.profile.GetAvatarCredentialResponse
	4,  // 43: org.signal.chat.profile.Profile.SetV1Avatar:output_type -> org.signal.chat.profile.SetV1AvatarResponse
	16, // 44: org.signal.chat.profile.ProfileAnonymous.GetProfile:output_type -> org.signal.chat.profile.GetProfileAnonymousResponse
	19, // 45: org.signal.chat.profile.ProfileAnonymous.GetProfileKeyCredential:output_type -> org.signal.chat.profile.GetProfileKeyCredentialResponse
	23, // 46: org.signal.chat.profile.ProfileAnonymous.GetAvatarUploadForm:output_type -> org.signal.chat.profile.GetAvatarUploadFormResponse
	25, // 47: org.signal.chat.profile.ProfileAnonymous.ExtendAvatarTTL:output_type -> org.signal.chat.profile.ExtendAvatarTTLResponse
	27, // 48: org.signal.chat.profile.ProfileAnonymous.DeleteAvatar:output_type -> org.signal.chat.profile.DeleteAvatarResponse
	40, // [40:49] is the sub-list for method output_type
	31, // [31:40] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_org_signal_chat_profile_proto_init() }
func file_org_signal_chat_profile_proto_init() {
	if File_org_signal_chat_profile_proto != nil {
		return
	}
	file_org_signal_chat_profile_proto_msgTypes[6].OneofWrappers = []any{}
	file_org_signal_chat_profile_proto_msgTypes[7].OneofWrappers = []any{
		(*SetProfileResponse_Result)(nil),
		(*SetProfileResponse_ExpectedDataWriteConflict)(nil),
		(*SetProfileResponse_PaymentsForbiddenInRegion)(nil),
		(*SetProfileResponse_ExpectedVersionWriteConflict)(nil),
	}
	file_org_signal_chat_profile_proto_msgTypes[9].OneofWrappers = []any{
		(*GetProfileAnonymousRequest_UnidentifiedAccessKey)(nil),
		(*GetProfileAnonymousRequest_GroupSendToken)(nil),
	}
	file_org_signal_chat_profile_proto_msgTypes[13].OneofWrappers = []any{
		(*GetProfileResponse_Profile)(nil),
		(*GetProfileResponse_EtagMatched)(nil),
		(*GetProfileResponse_NotFound)(nil),
		(*GetProfileResponse_LegacyProfile)(nil),
	}
	file_org_signal_chat_profile_proto_msgTypes[14].OneofWrappers = []any{
		(*GetProfileAnonymousResponse_Profile)(nil),
		(*GetProfileAnonymousResponse_EtagMatched)(nil),
		(*GetProfileAnonymousResponse_NotFound)(nil),
		(*GetProfileAnonymousResponse_FailedUnidentifiedAuthorization)(nil),
		(*GetProfileAnonymousResponse_ProfileV1)(nil),
	}
	file_org_signal_chat_profile_proto_msgTypes[17].OneofWrappers = []any{
		(*GetProfileKeyCredentialResponse_Result)(nil),
		(*GetProfileKeyCredentialResponse_NotFound)(nil),
		(*GetProfileKeyCredentialResponse_FailedUnidentifiedAuthorization)(nil),
	}
	file_org_signal_chat_profile_proto_msgTypes[19].OneofWrappers = []any{
		(*GetAvatarCredentialResponse_AvatarCredential)(nil),
		(*GetAvatarCredentialResponse_MissingZkCredentialKey)(nil),
	}
	file_org_signal_chat_profile_proto_msgTypes[21].OneofWrappers = []any{
		(*GetAvatarUploadFormResponse_AvatarUploadForm)(nil),
		(*GetAvatarUploadFormResponse_InvalidCredentialPresentation)(nil),
	}
	file_org_signal_chat_profile_proto_msgTypes[23].OneofWrappers = []any{
		(*ExtendAvatarTTLResponse_Path)(nil),
		(*ExtendAvatarTTLResponse_InvalidCredentialPresentation)(nil),
		(*ExtendAvatarTTLResponse_NotFound)(nil),
	}
	file_org_signal_chat_profile_proto_msgTypes[25].OneofWrappers = []any{
		(*DeleteAvatarResponse_Success)(nil),
		(*DeleteAvatarResponse_InvalidCredentialPresentation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_signal_chat_profile_proto_rawDesc), len(file_org_signal_chat_profile_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_org_signal_chat_profile_proto_goTypes,
		DependencyIndexes: file_org_signal_chat_profile_proto_depIdxs,
		EnumInfos:         file_org_signal_chat_profile_proto_enumTypes,
		MessageInfos:      file_org_signal_chat_profile_proto_msgTypes,
	}.Build()
	File_org_signal_chat_profile_proto = out.File
	file_org_signal_chat_profile_proto_goTypes = nil
	file_org_signal_chat_profile_proto_depIdxs = nil
}
